<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CoursesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('courses')->insert([
            // Humanities
            [
                'course_id' => 'ABH',
                'course_name' => 'Bachelor of Arts in History',
                'category_id' => 1,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'ABP',
                'course_name' => 'Bachelor of Arts in Philosophy',
                'category_id' => 1,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BFAD',
                'course_name' => 'Bachelor of Fine Arts Major in Industrial Design',
                'category_id' => 1,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BFAP',
                'course_name' => 'Bachelor of Fine Arts Major in Painting',
                'category_id' => 1,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BFAS',
                'course_name' => 'Bachelor of Fine Arts Major in Sculpture',
                'category_id' => 1,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BFAVC',
                'course_name' => 'Bachelor of Fine Arts Major in Visual Communication',
                'category_id' => 1,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Social Sciences
            [
                'course_id' => 'ABEC',
                'course_name' => 'Bachelor of Arts in Economics',
                'category_id' => 2,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSE',
                'course_name' => 'Bachelor of Science in Economics',
                'category_id' => 2,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'ABPSY',
                'course_name' => 'Bachelor of Arts in Psychology',
                'category_id' => 2,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSPSY',
                'course_name' => 'Bachelor of Science in Psychology',
                'category_id' => 2,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSCRIM',
                'course_name' => 'Bachelor of Science in Criminology',
                'category_id' => 2,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'ABPS',
                'course_name' => 'Bachelor of Arts in Political Science',
                'category_id' => 2,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'ABE',
                'course_name' => 'Bachelor of Arts in English',
                'category_id' => 2,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'ABL',
                'course_name' => 'Bachelor of Arts in Linguistics',
                'category_id' => 2,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'ABLIT',
                'course_name' => 'Bachelor of Arts in Literature',
                'category_id' => 2,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'ABA',
                'course_name' => 'Bachelor of Arts in Anthropology',
                'category_id' => 2,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'ABSOC',
                'course_name' => 'Bachelor of Arts in Sociology',
                'category_id' => 2,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'ABFIL',
                'course_name' => 'Bachelor of Arts in Filipino',
                'category_id' => 2,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSFnS',
                'course_name' => 'Bachelor of Science in Forensic Science',
                'category_id' => 2,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'ABISLAM',
                'course_name' => 'Bachelor of Arts in Islamic Studies',
                'category_id' => 2,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Natural Sciences
            [
                'course_id' => 'BSNES',
                'course_name' => 'Bachelor of Science in Environmental Science',
                'category_id' => 3,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSF',
                'course_name' => 'Bachelor of Science in Forestry',
                'category_id' => 3,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSFI',
                'course_name' => 'Bachelor of Science in Fisheries',
                'category_id' => 3,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSGEO',
                'course_name' => 'Bachelor of Science in Geology',
                'category_id' => 3,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSBIOL',
                'course_name' => 'Bachelor of Science in Biology',
                'category_id' => 3,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSMOLEC',
                'course_name' => 'Bachelor of Science in Molecular Biology',
                'category_id' => 3,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSPHY',
                'course_name' => 'Bachelor of Science in Physics',
                'category_id' => 3,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSAPPHY',
                'course_name' => 'Bachelor of Science in Applied Physics',
                'category_id' => 3,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSCH',
                'course_name' => 'Bachelor of Science in Chemistry',
                'category_id' => 3,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Formal Sciences
            [
                'course_id' => 'BSCS',
                'course_name' => 'Bachelor of Science in Computer Science',
                'category_id' => 4,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSIT',
                'course_name' => 'Bachelor of Science in Information Technology',
                'category_id' => 4,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSIS',
                'course_name' => 'Bachelor of Science in Information Systems',
                'category_id' => 4,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSMATH',
                'course_name' => 'Bachelor of Science in Mathematics',
                'category_id' => 4,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSAMATH',
                'course_name' => 'Bachelor of Science in Applied Mathematics',
                'category_id' => 4,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSSTAT',
                'course_name' => 'Bachelor of Science in Statistics',
                'category_id' => 4,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Agriculture
            [
                'course_id' => 'BSAGRI',
                'course_name' => 'Bachelor of Science in Agriculture',
                'category_id' => 5,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSABUS',
                'course_name' => 'Bachelor of Science in Agribusiness',
                'category_id' => 5,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSAF',
                'course_name' => 'Bachelor of Science in Agroforestry',
                'category_id' => 5,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSARCH',
                'course_name' => 'Bachelor of Science in Architecture',
                'category_id' => 5,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BLA',
                'course_name' => 'Bachelor in Landscape Architecture',
                'category_id' => 5,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSID',
                'course_name' => 'Bachelor of Science in Interior Design',
                'category_id' => 5,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Business
            [
                'course_id' => 'BSA',
                'course_name' => 'Bachelor of Science in Accountancy',
                'category_id' => 6,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSACT',
                'course_name' => 'Bachelor of Science in Accounting Technology',
                'category_id' => 6,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSBA',
                'course_name' => 'Bachelor of Science in Business Administration',
                'category_id' => 6,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSBA-BE',
                'course_name' => 'Bachelor of Science in Business Administration Major in Business Economics',
                'category_id' => 6,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSBA-FM',
                'course_name' => 'Bachelor of Science in Business Administration Major in Financial Management',
                'category_id' => 6,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSBA-HRDM',
                'course_name' => 'Bachelor of Science in Business Administration Major in Human Resource Development',
                'category_id' => 6,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSBA-MM',
                'course_name' => 'Bachelor of Science in Business Administration Major in Marketing Management',
                'category_id' => 6,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSBA-OM',
                'course_name' => 'Bachelor of Science in Business Administration Major in Operations Management',
                'category_id' => 6,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSHRM',
                'course_name' => 'Bachelor of Science in Hotel and Restaurant Management',
                'category_id' => 6,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSENTREP',
                'course_name' => 'Bachelor of Science in Entrepreneurship',
                'category_id' => 6,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSOA',
                'course_name' => 'Bachelor of Science in Office Administration',
                'category_id' => 6,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSREM',
                'course_name' => 'Bachelor of Science in Real Estate Management',
                'category_id' => 6,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSTM',
                'course_name' => 'Bachelor of Science in Tourism Management',
                'category_id' => 6,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Health Sciences
            [
                'course_id' => 'BSMT',
                'course_name' => 'Bachelor of Science in Medical Technology',
                'category_id' => 7,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSMIDWIFERY',
                'course_name' => 'Bachelor of Science in Midwifery',
                'category_id' => 7,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSN',
                'course_name' => 'Bachelor of Science in Nursing',
                'category_id' => 7,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSOT',
                'course_name' => 'Bachelor of Science in Occupational Therapy',
                'category_id' => 7,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSPHARMACY',
                'course_name' => 'Bachelor of Science in Pharmacy',
                'category_id' => 7,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSPT',
                'course_name' => 'Bachelor of Science in Physical Therapy',
                'category_id' => 7,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSRADTECH',
                'course_name' => 'Bachelor of Science in Radiologic Technology',
                'category_id' => 7,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSRT',
                'course_name' => 'Bachelor of Science in Respiratory Therapy',
                'category_id' => 7,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSSP',
                'course_name' => 'Bachelor of Science in Speech-Language Pathology',
                'category_id' => 7,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSSS',
                'course_name' => 'Bachelor of Science in Sports Science',
                'category_id' => 7,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Education
            [
                'course_id' => 'BSED',
                'course_name' => 'Bachelor in Secondary Education',
                'category_id' => 8,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BEED',
                'course_name' => 'Bachelor in Elementary Education',
                'category_id' => 8,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSEDTLE',
                'course_name' => 'Bachelor in Secondary Education Major in Technology and Livelihood Education',
                'category_id' => 8,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSEDBIO',
                'course_name' => 'Bachelor in Secondary Education Major in Biological Sciences',
                'category_id' => 8,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSEDENG',
                'course_name' => 'Bachelor in Secondary Education Major in English',
                'category_id' => 8,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSEDFIL',
                'course_name' => 'Bachelor in Secondary Education Major in Filipino',
                'category_id' => 8,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSEDMATH',
                'course_name' => 'Bachelor in Secondary Education Major in Mathematics',
                'category_id' => 8,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSEDISLAM',
                'course_name' => 'Bachelor in Secondary Education Major in Islamic Studies',
                'category_id' => 8,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSEDMAPE',
                'course_name' => 'Bachelor in Secondary Education Major in Music, Arts, Physical and Health Education',
                'category_id' => 8,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSEDPHYSCI',
                'course_name' => 'Bachelor in Secondary Education Major in Physical Sciences',
                'category_id' => 8,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSEDSS',
                'course_name' => 'Bachelor in Secondary Education Major in Social Studies',
                'category_id' => 8,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSEDEV',
                'course_name' => 'Bachelor in Secondary Education Major in Values Education',
                'category_id' => 8,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BEEDPE',
                'course_name' => 'Bachelor in Elementary Education Major in Preschool Education',
                'category_id' => 8,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BEEDSPED',
                'course_name' => 'Bachelor in Elementary Education Major in Special Education',
                'category_id' => 8,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BPE',
                'course_name' => 'Bachelor of Physical Education',
                'category_id' => 8,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Engineering
            [
                'course_id' => 'BSAeroE',
                'course_name' => 'Bachelor of Science in Aeronautical Engineering',
                'category_id' => 9,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSCerE',
                'course_name' => 'Bachelor of Science in Ceramic Engineering',
                'category_id' => 9,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSChE',
                'course_name' => 'Bachelor of Science in Chemical Engineering',
                'category_id' => 9,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSCE',
                'course_name' => 'Bachelor of Science in Civil Engineering',
                'category_id' => 9,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSCpE',
                'course_name' => 'Bachelor of Science in Computer Engineering',
                'category_id' => 9,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSEE',
                'course_name' => 'Bachelor of Science in Electrical Engineering',
                'category_id' => 9,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSECE',
                'course_name' => 'Bachelor of Science in Electronics and Communications Engineering',
                'category_id' => 9,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSGE',
                'course_name' => 'Bachelor of Science in Geodetic Engineering',
                'category_id' => 9,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSGeoE',
                'course_name' => 'Bachelor of Science in Geological Engineering',
                'category_id' => 9,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSIE',
                'course_name' => 'Bachelor of Science in Industrial Engineering',
                'category_id' => 9,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSMarE',
                'course_name' => 'Bachelor of Science in Marine Engineering',
                'category_id' => 9,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSMatE',
                'course_name' => 'Bachelor of Science in Materials Engineering',
                'category_id' => 9,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSME',
                'course_name' => 'Bachelor of Science in Mechanical Engineering',
                'category_id' => 9,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSMetE',
                'course_name' => 'Bachelor of Science in Metallurgical Engineering',
                'category_id' => 9,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSEM',
                'course_name' => 'Bachelor of Science in Mining Engineering',
                'category_id' => 9,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSPetE',
                'course_name' => 'Bachelor of Science in Petroleum Engineering',
                'category_id' => 9,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSSE',
                'course_name' => 'Bachelor of Science in Sanitary Engineering',
                'category_id' => 9,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Media and Communication
            [
                'course_id' => 'ABBroadcasting',
                'course_name' => 'Bachelor of Arts in Broadcasting',
                'category_id' => 10,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'ABCommunication',
                'course_name' => 'Bachelor of Arts in Communication',
                'category_id' => 10,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSDC',
                'course_name' => 'Bachelor of Science in Development Communication',
                'category_id' => 10,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'ABJournalism',
                'course_name' => 'Bachelor of Arts in Journalism',
                'category_id' => 10,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'ABMassCom',
                'course_name' => 'Bachelor of Arts in Mass Communication',
                'category_id' => 10,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Public Administration
            [
                'course_id' => 'BSCD',
                'course_name' => 'Bachelor of Science in Community Development',
                'category_id' => 11,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSCA',
                'course_name' => 'Bachelor of Science in Customs Administration',
                'category_id' => 11,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSFS',
                'course_name' => 'Bachelor of Science in Foreign Service',
                'category_id' => 11,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSInS',
                'course_name' => 'Bachelor of Science in International Studies',
                'category_id' => 11,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BPA',
                'course_name' => 'Bachelor of Public Administration',
                'category_id' => 11,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSPS',
                'course_name' => 'Bachelor of Science in Public Safety',
                'category_id' => 11,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSSW',
                'course_name' => 'Bachelor of Science in Social Work',
                'category_id' => 11,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Transportation
            [
                'course_id' => 'BSMrT',
                'course_name' => 'Bachelor of Science in Marine Transportation',
                'category_id' => 12,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Nutrition
            [
                'course_id' => 'BSFoodTech',
                'course_name' => 'Bachelor of Science in Food Technology',
                'category_id' => 13,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 'BSNutrition',
                'course_name' => 'Bachelor of Science in Nutrition and Dietetics',
                'category_id' => 13,
                'course_description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
